#https://artifacthub.io/packages/helm/kubeshark-helm-charts/kubeshark
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd
  # finalizers:
  #   # The default behaviour is foreground cascading deletion
  #   - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeshark
  project: development
  source:
    repoURL: https://helm.kubeshark.co
    targetRevision: 51.0.38
    chart: kubeshark
    helm:
      releaseName: kubeshark
      valuesObject:
        tap:
          ingress:
            enabled: true
            className: alb
            host: hello.azure.skotobaza.es
            tls: []
            annotations:
              kubernetes.io/ingress.class: "azure/application-gateway"
              appgw.ingress.kubernetes.io/backend-path-prefix: "/"
              appgw.ingress.kubernetes.io/appgw-ssl-certificate: "azure"
              appgw.ingress.kubernetes.io/ssl-redirect: "true"        
            finalizers:
            - ingress.k8s.aws/resources              
          release:
            namespace:
              kubeshark
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
