# #https://artifacthub.io/packages/helm/hello-helm-charts/hello
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: applications
  project: default
  source:
    repoURL: https://cloudecho.github.io/charts/
    targetRevision: 0.1.2
    chart: hello
    helm:
      releaseName: hello
      values: |
        ingress:
          enabled: true
          className: nginx
          annotations: {}
            kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
          hosts:
            - host: ks.svc.cluster.local
              paths:
                - path: /
                  pathType: ImplementationSpecific          
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
