# #https://artifacthub.io/packages/helm/hello-helm-charts/hello
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: applications
  project: development
  source:
    repoURL: https://cloudecho.github.io/charts/
    targetRevision: 0.1.2
    chart: hello
    helm:
      releaseName: hello
      valuesObject:
        ingress:
          enabled: true
          annotations:
              kubernetes.io/ingress.class: "azure/application-gateway"
              appgw.ingress.kubernetes.io/backend-path-prefix: "/"
              appgw.ingress.kubernetes.io/appgw-ssl-certificate: "azure"
              appgw.ingress.kubernetes.io/ssl-redirect: "true"    
          hosts:
            - host: hello.azure.skotobaza.es
              paths:
                - path: /
                  pathType: ImplementationSpecific
  syncPolicy:
    automated:
      selfHeal: true
      prune: true